name: Render video
on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      subtitleText:
        description: "Which text should it say?"
        required: true
        default: "With these powerful tools, what will you build?"
      voice:
        description: "Voice name"
        required: true
        default: "Woman 1 (US)"
      pitch:
        description: "Pitch of the voice"
        required: true
        default: 0
      speakingRate:
        description: "Speaking rate of the voice"
        required: true
        default: 1
      audioUrl:
        description: "URL of the voice audio"
        required: true
        default: null
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update

      - run: sudo apt install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./input-props.json"
        env:
          SERVER_PORT: ${{secrets.SERVER_PORT}}
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
          FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

          # NOT REQUIRED IF YOU USE `GOOGLE_APPLICATION_CREDENTIALS`

          # GOOGLE_CLOUD_PRIVATE_KEY: ${{secrets.GOOGLE_CLOUD_PRIVATE_KEY}}
          # GOOGLE_CLOUD_CLIENT_EMAIL: ${{secrets.GOOGLE_CLOUD_CLIENT_EMAIL}}
          # GOOGLE_CLOUD_CLIENT_ID: ${{secrets.GOOGLE_CLOUD_CLIENT_ID}}

      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4
